name: CI-develop

on: 
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.100
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Build with dotnet
      run: dotnet build --configuration Release ./IctBaden.Framework.sln
    - name: Test with dotnet
      env: 
        SkipPerformanceTests: true
      run: dotnet test ./IctBaden.Framework.sln --configuration Release
